import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { renderToBuffer } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import React from 'react';
import type { GeneratedCV } from '@/types';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#D4A012', paddingBottom: 10 },
  name: { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 11, color: '#666' },
  section: { marginBottom: 14 },
  sectionTitle: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#D4A012', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 1 },
  text: { fontSize: 10, lineHeight: 1.5, marginBottom: 4 },
  skillCategory: { fontFamily: 'Helvetica-Bold', fontSize: 10, marginBottom: 2 },
  row: { flexDirection: 'row', marginBottom: 6 },
  roleTitle: { fontFamily: 'Helvetica-Bold', fontSize: 10 },
  roleYears: { fontSize: 9, color: '#666', marginLeft: 8 },
  watermark: { position: 'absolute', bottom: 20, right: 40, fontSize: 8, color: '#ccc' },
});

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });

  const { data: candidate } = await supabase
    .from('candidate_profiles')
    .select('generated_cv, tier, user_id')
    .eq('user_id', user.id)
    .single();

  if (!candidate || !candidate.generated_cv) {
    return NextResponse.json({ error: 'No CV generated yet' }, { status: 404 });
  }
  if (candidate.tier !== 'complete') {
    return NextResponse.json({ error: 'Complete tier required for PDF download' }, { status: 403 });
  }

  const { data: profile } = await supabase
    .from('profiles')
    .select('first_name, last_name')
    .eq('id', user.id)
    .single();

  const name = profile ? `${profile.first_name} ${profile.last_name}` : 'Candidate';

  try {
    const cv = candidate.generated_cv as unknown as GeneratedCV;
    const doc = React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        React.createElement(View, { style: styles.header },
          React.createElement(Text, { style: styles.name }, name),
          React.createElement(Text, { style: styles.subtitle }, 'Household Professional')
        ),
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Professional Summary'),
          React.createElement(Text, { style: styles.text }, cv.professional_summary)
        ),
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Skills & Competencies'),
          ...(cv.skills_competencies || []).map((cat: any, i: number) =>
            React.createElement(View, { key: String(i), style: { marginBottom: 4 } },
              React.createElement(Text, { style: styles.skillCategory }, cat.category),
              React.createElement(Text, { style: styles.text }, (cat.skills || []).join(' · '))
            )
          )
        ),
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Professional Experience'),
          ...(cv.professional_experience || []).map((exp: any, i: number) =>
            React.createElement(View, { key: String(i), style: { marginBottom: 6 } },
              React.createElement(View, { style: styles.row },
                React.createElement(Text, { style: styles.roleTitle }, exp.role),
                React.createElement(Text, { style: styles.roleYears }, exp.years)
              ),
              React.createElement(Text, { style: styles.text }, exp.description)
            )
          )
        ),
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Languages'),
          React.createElement(Text, { style: styles.text },
            (cv.languages || []).map((l: any) => `${l.language} (${l.proficiency})`).join(' · ')
          )
        ),
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Availability'),
          React.createElement(Text, { style: styles.text }, `${cv.availability || 'Not specified'} · ${(cv.location_preferences || []).join(', ')}`),
          React.createElement(Text, { style: styles.text }, cv.salary_expectation || '')
        ),
        React.createElement(Text, { style: styles.watermark }, 'Generated by HouseHoldTalent')
      )
    );
    const buffer = await renderToBuffer(doc as any);

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${name.replace(/\s+/g, '-')}-CV.pdf"`,
      },
    });
  } catch {
    console.error('PDF generation failed');
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 });
  }
}
